export const spamWords = [
    // Financial lures
    'free',
    'winner',
    'win',
    'prize',
    'cash',
    'urgent',
    'limited time',
    'risk-free',
    'guaranteed',
    'no obligation',
    'no charge',
    'act now',
    'exclusive deal',
    'click here',
    'subscribe now',
    'buy now',
    'get paid',
    'easy money',
    'fast cash',
    'seo',
    'near the top of the rankings',
    'demo',
    
    // Additional financial terms
    'discount',
    'save money',
    'bargain',
    'cheap',
    'affordable',
    'lowest price',
    'best rates',
    'no hidden fees',
    'investment opportunity',
    'debt relief',
    'earn from home',
    'passive income',
    'double your money',
    'income stream',
    'refinance',
    'lottery',
    'jackpot',
    
    // Questionable products/services
    'viagra',
    'cialis',
    'pharmacy',
    'prescription',
    'weight loss',
    'diet pill',
    'enlarge',
    'enhancement',
    'crypto',
    'bitcoin',
    'forex',
    'trading',
    'casino',
    'poker',
    'slots',
    'betting',
    'gambling',
    
    // Pressure tactics
    'limited offer',
    'don\'t delete',
    'don\'t miss out',
    'once in a lifetime',
    'while supplies last',
    'time sensitive',
    'expires today',
    'call now',
    'apply now',
    'instant approval',
    'congratulations',
    'selected',
    'you\'ve been chosen',
    
    // Other common spam indicators
    'no spam',
    'not spam',
    'this is not spam',
    'unsubscribe',
    'opt out',
    'bulk email',
    'marketing',
    'miracle',
    'breakthrough',
    'amazing',
    'secret of',
    'revealed',
    'discovery',
    'revolutionary',
    'transform your life',
    'change your life',
    
    // Contact/URL manipulation
    'dear webmaster',
    'dear website owner',
    'contact list',
    'mailing list',
    'click below',
    'click the link',
    'hidden',
    'privately',
    'confidential',
    
    // Technical spam
    'traffic generation',
    'website traffic',
    'backlinks',
    'guaranteed ranking',
    'search engine submission',
    'social media marketing',
    'digital marketing',
    'link building',
    'web development services',
    'web design services'
];