export const spamWords = [
    // Financial scams
    'winner',
    'prize',
    'cash',
    'urgent',
    'risk-free',
    'guaranteed',
    'no obligation',
    'no charge',
    'act now',
    'exclusive deal',
    'get paid',
    'easy money',
    'fast cash',
    'seo',
    'near the top of the rankings',
    'work from home',
    'earn money',
    'quick cash',
    'make money fast',
    'financial freedom',
    'wealth building',
    'high returns',
    'investment scheme',
    'pyramid scheme',
    'mlm',
    'multi level marketing',
    
    // Questionable products/services
    'viagra',
    'cialis',
    'pharmacy',
    'prescription',
    'weight loss',
    'diet pill',
    'enlarge',
    'enhancement',
    'crypto',
    'bitcoin',
    'forex',
    'trading',
    'casino',
    'poker',
    'slots',
    'betting',
    'gambling',
    'dietary supplement',
    'health supplement',
    'male enhancement',
    'penis enlargement',
    'breast enhancement',
    'anti aging',
    'wrinkle cream',
    'acne treatment',
    'hair loss',
    'weight loss supplement',
    'fat burner',
    'diet pill',
    'muscle building',
    'steroid',
    'nft',
    'token',
    'ico',
    'initial coin offering',
    
    // Pressure tactics
    'limited offer',
    'don\'t delete',
    'don\'t miss out',
    'once in a lifetime',
    'while supplies last',
    'time sensitive',
    'expires today',
    'call now',
    'apply now',
    'instant approval',
    'congratulations',
    'selected',
    'you\'ve been chosen',
    'last chance',
    'final notice',
    'urgent response required',
    'immediate action required',
    'limited time only',
    'exclusive opportunity',
    'special promotion',
    'limited availability',
    'first come first serve',
    'act fast',
    'don\'t wait',
    'hurry up',
    
    // Other common spam indicators
    'no spam',
    'not spam',
    'this is not spam',
    'unsubscribe',
    'opt out',
    'bulk email',
    'miracle',
    'breakthrough',
    'secret of',
    'revealed',
    'discovery',
    'revolutionary',
    'transform your life',
    'change your life',
    'life changing',
    'never before seen',
    'exclusive access',
    'insider information',
    'confidential information',
    'private offer',
    'special access',
    'vip access',
    'exclusive membership',
    'premium access',
    'limited access',
    
    // Contact/URL manipulation
    'dear webmaster',
    'dear website owner',
    'contact list',
    'mailing list',
    'click below',
    'click the link',
    'hidden',
    'privately',
    'confidential',
    'dear sir',
    'dear madam',
    'dear friend',
    'dear valued customer',
    'dear website visitor',
    'dear internet user',
    'dear email user',
    'dear account holder',
    'dear member',
    'dear subscriber',
    'dear customer',
    'dear client',
    'dear partner',
    'dear associate',
    'dear colleague',
    'dear business owner',
    
    // Technical spam
    'traffic generation',
    'website traffic',
    'backlinks',
    'guaranteed ranking',
    'search engine submission',
    'social media marketing',
    'digital marketing',
    'link building',
    'web development services',
    'web design services',
    'seo services',
    'seo optimization',
    'seo package',
    'seo expert',
    'seo specialist',
    'seo consultant',
    'seo agency',
    'seo company',
    'seo firm',
    'seo professional',
    'seo master',
    'seo guru',
    'seo wizard',
    'seo ninja',
    'seo rockstar'
];